mongo:
  uri: "mongodb://localhost:27017"
  database: "hug_db"
  collection: "audios"


s3:
  endpoint: "127.0.0.1:9000"      # MinIO 服务地址（不带 https://）
  bucket: "hug"                   # 桶名
  region: "us-east-1"             # MinIO 默认是 us-east-1，可不改
  access_key: "minioadmin"        # 默认账号
  secret_key: "minioadmin"        # 默认密码
  use_ssl: false                  # 本地环境一般不启用 SSL

tmp_dir: "/tmp"                  # 临时文件目录